### ISSUE TITLE
Login issues for Open Discussions RC

### ISSUE THREAD

**Issue by pedroclarkleite** [mitodl/ol-keycloak#21]
Hello, 

When I tried to access https://discussions-rc.odl.mit.edu/login/ol-oidc/ I got an application error from Heroku. 

## Expected Behavior
I was expecting to be logged in the release candidate instance for OD 

## Current Behavior
Application Error: 
"An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail" 

## Steps to Reproduce
1. Login https://discussions-rc.odl.mit.edu/login/ol-oidc/

**Comment by shaidar** [comment]
Should be working now. The issue was the discussions app had expired credentials.

**Comment by pedroclarkleite** [comment]
Thanks @shaidar . Do you have any probes in order to monitor when certificates are about to expire so we don't face that in production in the future? I know that Heroku has some APIs and some automatic certificate renewal jobs...

**Comment by pedroclarkleite** [comment]
@pdpinch FYI - the issue with OD was solved (credentials expired)

**Comment by pedroclarkleite** [comment]
Ok perfect then! Thanks for the quick fix :)

**Comment by pedroclarkleite** [comment]
@shaidar , @pdpinch just asked me if we could add an automated probe/testing also to the RC instance because we still have a lot of (internal) folks using that as a reference, and it may be a blocker if they can't log in. It's not a hard requirement, but if we have it and ensure it works, it may avoid some friction.

**Comment by shaidar** [comment]
Looks like an alert was triggered for RC however we had been having issues on salt-master QA which didn't allow us to update any creds for our Heroku QA apps until later in the day. So we should already be set on this.
